version: '3.8'

services:
  api:
    build:
      context: ./services/api
    ports:
      - "7000:7000"
    env_file:
      - ./services/api/.env

  websocket:
    build:
      context: ./services/websocket
    ports:
      - "7001:7001"
    env_file:
      - ./services/websocket/.env

  worker:
    build:
      context: ./services/worker
    env_file:
      - ./services/worker/.env

  nginx:
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api
      - websocket
